### ISSUE TITLE
Deployment gracefully shutdown

### ISSUE THREAD

**Issue by hebertdougl** [CircleCI-Public/circleci-runner-k8s#21]
Hello everyone,

In the runner config reference documentation, the way to gracefully shutdown a runner is [mentioned](https://circleci.com/docs/runner-config-reference#customizing-job-timeouts-and-drain-timeouts), this happens when a TERM signal is sent to the process. I think as an improvement we can add a `preStop` hook to the deployment in order to prevent agents from being interrupted abruptly. It would be something like:
```
      containers:
        - name: {{ .Chart.Name }}

          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - "kill -15 $(pidof circleci-launch-agent);"

```
Do you think that would be necessary in this case? If you want I can do the PR with the modifications.
